name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout

jobs:
  call:
    uses: portabletext/.github/.github/workflows/changesets-from-conventional-commits.yml@74d23476005e7eae2984e2e408d06d6669d1b300 # main
    if: github.event.pull_request.user.login == 'renovate[bot]'
    secrets: inherit
