name: Create Release Pull Request or Publish to npm with Changesets

on:
  workflow_call:
    inputs:
      repository:
        required: true
        description: 'The repository to allow changesets to be created in, to prevent attempting to run changesets from a fork'
        type: string
      TURBO_TEAM:
        required: false
        description: 'Needed for using turborepo with remote caching'
        type: string
    secrets:
      ECOSCRIPT_APP_ID:
        required: true
      ECOSCRIPT_APP_PRIVATE_KEY:
        required: true
      TURBO_TOKEN:
        required: false
        description: 'Needed for using turborepo with remote caching'
      

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read # for checkout
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  changesets:
    if: github.repository == inputs.repository
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
    permissions:
      contents: read # for checkout
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.ECOSCRIPT_APP_ID }}
          private-key: ${{ secrets.ECOSCRIPT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # Uses generated token to allow pushing commits back
          token: ${{ steps.app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*
        # temporary until setup-node action comes with npm version that contains oidc setup by default
      - run: npm install -g npm@latest
      - run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1.5.2
        with:
          publish: pnpm release
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_CONFIG_PROVENANCE: true
