name: Add changeset to Renovate updates

on:
  workflow_call:
    inputs:
      user-login:
        required: true
        type: string
        description: Should be github.event.pull_request.user.login
    secrets:
      ECOSCRIPT_APP_ID:
        required: true
      ECOSCRIPT_APP_PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.user.login == 'renovate[bot]'
    steps:
      - name: 'github.event.pull_request.user.login'
        run: echo ${{ github.event.pull_request.user.login }}
      - name: 'user-login'
        run: echo ${{ inputs.user-login }}
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.ECOSCRIPT_APP_ID }}
          private-key: ${{ secrets.ECOSCRIPT_APP_PRIVATE_KEY }}
      - uses: mscharley/dependency-changesets-action@9ed25d74aded420840fa0264625c26f1443d13da # v1.1.8
        with:
          token: ${{ steps.app-token.outputs.token }}
          use-conventional-commits: true
          sign-commits: true
